# Server Configuration
server.port=${PORT:8080}
spring.application.name=DocuQuery

# Gemini AI Configuration
gemini.api.key=${GEMINI_API_KEY}

# Multipart File Upload Configuration
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB